config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('jat.urls')),
    path('admin/', admin.site.urls),
]

jat/urls.py
from django.urls import path

from jat import views

app_name = 'jat'

urlpatterns = [
    path('', views.RepositoryListView.as_view(), name='repository_list'),    #jat:repository_list
    path('repository/<int:pk>/', views.RepositoryDetailView.as_view(), name='repository_detail'),    #jat:repository_detail
    path('repository/<int:repository_pk>/introduction/<int:pk>/', views.IntroductionDetailView.as_view(), name='introduction_detail'),    #jat:introduction_detail
    path('repository/add/', views.RepositoryCreateView.as_view(), name='repository_add'),    #jat:repository_add
    path('repository/<int:pk>/modify/', views.RepositoryUpdateView.as_view(), name='repository_modify'),    #jat:repository_modify
    path('repository/<int:pk>/delete/', views.RepositoryDeleteView.as_view(), name='repository_delete'),    #jat:repository_delete
    path('repository/<int:repository_pk>/introduction/add/', views.IntroductionCreateView.as_view(), name='introduction_add'),
    path('repository/<int:repository_pk>/introduction/<int:pk>/modify/', views.IntroductionUpdateView.as_view(), name='introduction_modify'),
    path('repository/<int:repository_pk>/introduction/<int:pk>/delete/', views.IntroductionDeleteView.as_view(), name='introduction_delete'),
]

jat/models.py
from django.db import models


class Repository(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    deadline = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # repo1.introduction_set
    class Meta:
        verbose_name_plural = 'Repositories'
        ordering = ['deadline']

    def __str__(self):
        return self.name


class Introduction(models.Model):
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)  # intro1.repository
    version = models.IntegerField(default=1)
    contents = models.TextField()
    access = models.IntegerField(default=1)  # 0: private, 1: public

    # intro1.comment_set
    class Meta:
        ordering = ['-version']

    def __str__(self):
        return f'{self.version} {self.contents}'


class Comment(models.Model):
    introduction = models.ForeignKey(Introduction, on_delete=models.CASCADE)  # comm1.introduction
    comment = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.comment

jat/views.py
from django.db.models import Max
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from jat.models import Repository, Introduction


class RepositoryListView(generic.ListView):
    model = Repository


class RepositoryDetailView(generic.DetailView):
    model = Repository


class RepositoryCreateView(generic.CreateView):
    model = Repository
    fields = ['name', 'description', 'deadline']  # '__all__'
    template_name_suffix = '_create'
    success_url = reverse_lazy('jat:repository_list')


class RepositoryUpdateView(generic.UpdateView):
    model = Repository
    fields = ['name', 'description', 'deadline']  # '__all__'
    template_name_suffix = '_update'
    success_url = reverse_lazy('jat:repository_list')


class RepositoryDeleteView(generic.DeleteView):
    model = Repository
    success_url = reverse_lazy('jat:repository_list')


class IntroductionDetailView(generic.DetailView):
    model = Introduction


class IntroductionCreateView(generic.CreateView):
    model = Introduction
    fields = ['repository', 'version', 'contents', 'access']  # '__all__'
    template_name_suffix = '_create'

    # success_url = reverse_lazy('jat:repository_detail') #repository_detail은 pk가 필요함(ImproperlyConfigured at /repository/3/introduction/add/)
    def get_initial(self):
        repository = get_object_or_404(Repository, pk=self.kwargs['repository_pk'])
        introduction = repository.introduction_set.aggregate(
            Max('version'))  # 해당 repository의 introduction 중 version 최대값 구하자
        version = introduction['version__max']
        if version == None:  # introduction이 아예 없으면 version 기본값: 1
            version = 1
        else:  # introduction이 있으면 version 최대값에서 +1
            version += 1
        return {'repository': repository, 'version': version}

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})


class IntroductionUpdateView(generic.UpdateView):
    model = Introduction
    fields = ['repository', 'version', 'contents', 'access']  # '__all__'
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})


class IntroductionDeleteView(generic.DeleteView):
    model = Introduction

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

jat/templates/jat/introduction_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Do you want to delete Introduction "{{ introduction }}"?
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back();">Cancel</button>
    </form>
{% endblock %}

jat/templates/jat/introduction_create.html
{% extends 'base.html' %}

{% block title %}Add Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

jat/templates/jat/introduction_detail.html
{% extends 'base.html' %}

{% block title %}Detail Introduction{% endblock %}

{% block content %}
    {{ introduction.contents }}
    <table border="1">
        <tbody>
        {% for comment in introduction.comment_set.all %}
            <tr>
                <td>{{ comment.comment }}</td>
                <td>수정</td>
                <td>삭제</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/introduction_update.html
{% extends 'base.html' %}

{% block title %}Update Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

jat/templates/jat/repository_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Do you want to delete Repository "{{ repository }}"?
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back();">Cancel</button>
    </form>
{% endblock %}

jat/templates/jat/repository_create.html
{% extends 'base.html' %}

{% block title %}Add Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

jat/templates/jat/repository_detail.html
{% extends 'base.html' %}

{% block title %}Detail Repository{% endblock %}

{% block content %}
    {{ repository.name }}
    <a href="{% url 'jat:introduction_add' repository_pk=repository.pk %}">Add Introduction</a>
    <table border="1">
        <tbody>
        {% for introduction in repository.introduction_set.all %}
            <tr>
                <td>Version: <a href="{% url 'jat:introduction_detail' repository_pk=repository.pk pk=introduction.pk %}">{{ introduction.version }}</a></td>
                <td><a href="{% url 'jat:introduction_delete' repository_pk=repository.pk pk=introduction.pk %}">삭제</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/repository_list.html
{% extends 'base.html' %}

{% block title %}List Repository{% endblock %}

{% block content %}
    {{ repository_list.count }} Repository
    <a href="{% url 'jat:repository_add' %}">Add Repository</a>
    <table border="1">
        <tbody>
        {% for repository in repository_list %}
            <tr>
                <td><a href="{% url 'jat:repository_modify' pk=repository.pk %}">수정</a></td>
                <td><a href="{% url 'jat:repository_detail' pk=repository.pk %}">{{ repository.name }}</a></td>
                <td>Date: {{ repository.deadline }}</td>
                <td><a href="{% url 'jat:repository_delete' pk=repository.pk %}">삭제</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/repository_update.html
{% extends 'base.html' %}

{% block title %}Update Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <button type="submit">Update</button>
    </form>
{% endblock %}